from textual.theme import Theme

hacker_terminal = Theme(
    name="hacker-terminal",
    primary="#00cc00",      
    secondary="#2EB82E",    
    accent="#1F8F1F",       
    foreground="#33CC33",   
    background="#1E1E1E",   
    surface="#2A2A2A",      
    panel="#333333",        
    success="#33CC33",      
    warning="#88CC88",      
    error="#FF5555",        
    dark=True,
    variables={
        "border": "#33CC33",
        "border-blurred": "#224422",
        "block-cursor-foreground": "#1E1E1E",
        "block-cursor-background": "#33CC33",
        "input-selection-background": "#33CC3340",
        "footer-key-foreground": "#33CC33",
    },
)

dark_matter = Theme(
    name="dark-matter",
    primary="#6272A4",      
    secondary="#44475A",    
    accent="#50FA7B",       
    foreground="#E0E0FF",   
    background="#0F0F1A",   
    surface="#1E1E2E",      
    panel="#28293D",        
    success="#50FA7B",
    warning="#F1FA8C",
    error="#FF5555",
    dark=True,
    variables={
        "border": "#6272A4",
        "border-blurred": "#2E2F3D",
        "block-cursor-foreground": "#0F0F1A",
        "block-cursor-background": "#6272A4",
        "input-selection-background": "#6272A440",
        "footer-key-foreground": "#50FA7B",
    },
)

forest = Theme(
    name="forest",
    primary="#6B8E23",      
    secondary="#556B2F",    
    accent="#8FBC8F",       
    foreground="#E6E6DD",   
    background="#2B2D24",   
    surface="#32362C",      
    panel="#39402F",        
    success="#6B8E23",
    warning="#C4A000",
    error="#B22222",
    dark=True,
    variables={
        "border": "#6B8E23",
        "border-blurred": "#2A2D22",
        "block-cursor-foreground": "#2B2D24",
        "block-cursor-background": "#6B8E23",
        "input-selection-background": "#6B8E2340",
        "footer-key-foreground": "#8FBC8F",
    },
)

retro_wave = Theme(
    name="retro-wave",
    primary="#FF357C",      
    secondary="#7E57C2",    
    accent="#35EFFF",       
    foreground="#F8F8F2",   
    background="#1E1B29",   
    surface="#2A2637",      
    panel="#322D41",        
    success="#50FA7B",
    warning="#F1FA8C",
    error="#FF6E6E",
    dark=True,
    variables={
        "border": "#FF357C",
        "border-blurred": "#3A3347",
        "block-cursor-foreground": "#1E1B29",
        "block-cursor-background": "#FF357C",
        "input-selection-background": "#FF357C40",
        "footer-key-foreground": "#7E57C2",
    },
)

desert_night = Theme(
    name="desert-night",
    primary="#8B5E3C",      
    secondary="#70492B",    
    accent="#B89067",       
    foreground="#EDE6DD",   
    background="#2B2A2E",   
    surface="#362E2E",      
    panel="#4B3A38",        
    success="#9ABEB7",      
    warning="#D9B47B",      
    error="#E9724C",        
    dark=True,
    variables={
        "border": "#8B5E3C",                   
        "border-blurred": "#4A2E1F",           
        "block-cursor-foreground": "#2B2A2E",  
        "block-cursor-background": "#8B5E3C",  
        "input-selection-background": "#8B5E3C40", 
        "footer-key-foreground": "#B89067",    
    },
)