from textual.theme import Theme

hacker_terminal = Theme(
    name="hacker-terminal",
    primary="#00cc00",      
    secondary="#2EB82E",    
    accent="#1F8F1F",       
    foreground="#33CC33",   
    background="#1E1E1E",   
    surface="#2A2A2A",      
    panel="#333333",        
    success="#33CC33",      
    warning="#88CC88",      
    error="#FF5555",        
    dark=True,
    variables={
        "border": "#33CC33",
        "border-blurred": "#224422",
        "block-cursor-foreground": "#1E1E1E",
        "block-cursor-background": "#33CC33",
        "input-selection-background": "#33CC3340",
        "footer-key-foreground": "#33CC33",
    },
)

monochrome_minimal = Theme(
    name="monochrome-minimal",
    primary="#FFFFFF",      
    secondary="#EEEEEE",    
    accent="#CCCCCC",       
    foreground="#FFFFFF",   
    background="#000000",   
    surface="#111111",      
    panel="#222222",        
    success="#00FF00",
    warning="#FFFF00",
    error="#FF0000",
    dark=True,
    variables={
        "border": "#FFFFFF",
        "border-blurred": "#444444",
        "block-cursor-foreground": "#000000",
        "block-cursor-background": "#FFFFFF",
        "input-selection-background": "#FFFFFF40",
        "footer-key-foreground": "#EEEEEE",
    },
)

moonstone = Theme(
    name="moonstone",
    primary="#6FA3A3",      
    secondary="#5E7A7A",    
    accent="#A3C4BC",       
    foreground="#E3E3E3",   
    background="#1F2128",   
    surface="#2A2D34",      
    panel="#34384D",        
    success="#8EBF87",
    warning="#D0A15E",
    error="#BF616A",
    dark=True,
    variables={
        "border": "#6FA3A3",
        "border-blurred": "#2F3138",
        "block-cursor-foreground": "#1F2128",
        "block-cursor-background": "#6FA3A3",
        "input-selection-background": "#6FA3A340",
        "footer-key-foreground": "#A3C4BC",
    },
)

ember = Theme(
    name="ember",
    primary="#C57E5A",      
    secondary="#9C5A4E",    
    accent="#DAB985",       
    foreground="#E8E8E8",   
    background="#1E1C1F",   
    surface="#2C2A2D",      
    panel="#353335",        
    success="#8EBF87",
    warning="#D0A15E",
    error="#BF616A",
    dark=True,
    variables={
        "border": "#C57E5A",
        "border-blurred": "#3A383A",
        "block-cursor-foreground": "#1E1C1F",
        "block-cursor-background": "#C57E5A",
        "input-selection-background": "#C57E5A40",
        "footer-key-foreground": "#DAB985",
    },
)

dusk_violet = Theme(
    name="dusk-violet",
    primary="#8A6EA3",      
    secondary="#6E5980",    
    accent="#B39DBF",       
    foreground="#EAE8EE",   
    background="#1D1B23",   
    surface="#2B2930",      
    panel="#33303A",        
    success="#8EBF87",
    warning="#D0A15E",
    error="#BF616A",
    dark=True,
    variables={
        "border": "#8A6EA3",
        "border-blurred": "#3A383F",
        "block-cursor-foreground": "#1D1B23",
        "block-cursor-background": "#8A6EA3",
        "input-selection-background": "#8A6EA340",
        "footer-key-foreground": "#B39DBF",
    },
)
